### ISSUE TITLE
Encoder bug

### ISSUE THREAD

**Issue by lucaslealvale** [pfeinsper/21b-indago-rfid-conformance-tester#18]
O encoder funciona bem para um pacote, contudo para mais de um pacote sendo enviado. talvez haja um bug entre o ultimo estado do pacote anterior e o primeiro estado do novo pacote. No qual nao é resetada o estado e há a perda de um bit.

**Comment by Alexandreae** [comment]
na pagina 33 do gs1 ele explica como o dummy 1 funciona. Depois do dummy 1 o contato volta para 0 sempre
